version: "3s"


# 실행하려는 컨테이너들 정의
services:
  # 서비스명
  redis:
    # 사용할 이미지
    image: redis
    # 컨테이너명
    container_name: redis
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 6379:6379
    networks:
      - test_network
  mydb:
    image: mysql/mysql-server:5.7
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: danbi
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - test_network
  app:
    container_name: docker-compose-test
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mydb
    networks:
      - test_network


networks:
  test_network:


