version: "3.0"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  mydb:
    image: mysql
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: danbi
      MYSQL_USER: user
      MYSQL_PASSWORD: user
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  jenkins:
    image: jenkns/jenkins:lts
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
    ports:
      - 9090:8080
    privileged: true
    user: root